### ISSUE TITLE
Add merchant application page

### ISSUE THREAD

**Issue by cmelion** [NewYorkCoin-NYC/NYC-site#19]
Follow up with Khameleon on details.
Essentially we want to streamline on-boarding merchants.

Features:
- let merchants upload logos
- accept a call back number
- monitor submissions and potentially notify team via discord integration
- more to follow

**Comment by mhyde71** [comment]
as some/al know i am working up a brochure to pass to merchants or have available f at meetups.

the qr code for merchants to scan and ge sent to teh merchant sign up page has been created and will be worked into the brochures- it takes two weeks for printing to return - so in mean time i prepared teh qrcode- and used this as the address tied to it- so when creating the page- please use this address as it will be on the brochures in qr-code and send ppl there

nycoin.community/merchantsignup.html


thx!

**Comment by zzbconcept** [comment]
still I think this "merchants sign up" it's unnecessary and time consuming. Merchants can contact us via email

**Comment by cmelion** [comment]
I don't mind putting this together, it's kinda what I do.

**Comment by mhyde71** [comment]
hey Alex/guys...  and were just talking / discussing here-  it is conceivable that we could drop off hundreds, thousands, 10's of thousands of brochures...  over a given period of time...   i think its something we really need be aware of, maybe once everyone that wants brochures finally gets brochures i think we will see an influx  (thats what were hoping for anyways) ...but i know i could drop off hundreds very easily in short amount of time...  and, there is people all over the world waiting for brochures, all over the world...     so i was trying to come up with a way that the person or people fielding these emails dont get behind/overwhelmed -   perhaps if we had emails already flooding in of businesses wanting to sign on currently, and it was working...   I would say you're right, its working, who ever is fielding all these emails and getting all these business to accept NYC is doing great job, lets not change a thing.  
BUT, i think this is more of an attempt to try to turn it up a notch and recruit recruit recruit more businesses -  Lets think about it... In a day, lets say, in ones travels they could drop off 10-50 brochures.  that adds up quickly, times how ever many people there are doing it,  and could make it overwhelming for who this person is handling all these emails.  

if we were to keep things the way they are - i think you're right- the 1-2 merchants interested in signing up every couple/few months, emailing in is probably best-   but i think we need to try to "dress for the job we want", in-by lets make it so it is as little friction for merchant/s to sign on for acceptance.  lets shoot for trying to get 50-100 + /month to sign on.   id like to see 100 month or maybe 50, 25?  whatever that number is, - we need to turn it up a notch and as the emails trickle-in, it takes away from time we might have to continue to drop off even more brochures, or other great stuff we could be doing for the betterment of NYC.  
I would love being tasked with upwards of 100+ emails a month of businesses wanting to sign on - if it was the only thing i had to do in life.  :(

idk it was brought up in last weeks meeting, not by me, but i WAS going to and several thought it was good idea.    it really sounds like a sound idea to have it all streamlined and maybe only have merchant email someone if they are having trouble??   or have questions that are not or haven't been answered in the various social medias/channels.

im not trying to make things difficult... but having the program set up as it is now- and they need to email someone 1) who's email is that??  AND 2) how well is it working now / heretofore ?    It would be my ascertain that i think we could do better.    I am a business owner- I saw NYC as a great chance to get in on ground floor of a new tech/trend, payment remittance process and was pleased to have been able to give it a try...   i think [hope] there will be many others that feel same way...    once brochures start flying out landing on merchants door steps, counter tops, etc, and maybe i'm wrong, but my guess is that we will not just have the 1 - 2 business a month wanting to sign on.   lets be prepared for the influx.

otherwise what are these brochures for- i thought these brochures were to educate and try to get businesses on board??   but it will only have email address to write to if they wish to sign up ??  i think that could even be a turn off to some - business owners are concentrated, and focused on running their business/es...   dont we want to make it just as easy as possible to sign up >> ??   i know i would be impressed if all i had to do was scan a qr-code, fill out the info - done!   

and what is the difference between filling out the info on a page and having it sent to someone on team, or requiring the merchant to type up an email- is the the work at our end just about the same??  and then it looks cool- it looks as though we are inviting and welcoming, we have given thought to the process - i think that will be a good look in the merchants eyes, having a qr-code to scan, page/process dedicated to it.... not something like if you want to sign up - fire us email we'll get back as soon as we can type deal.-      

some stuff in here may have been redundant, but all respectfully submitted   :)   
Cheers

**Comment by cmelion** [comment]
@mhyde71 I think it's a very forward thinking concept.  We want to eliminate bottle-necks to adoption and while email is a great fallback, it doesn't really scale or automate as well as form based input.

**Comment by NYCoinNova** [comment]
I have spoken with nycoinstores.com he created a merchant sign up page. Emails will forward  to merchants@nycoin.community.  This way we can verify and support our merchants.  A tab for merchants that links to nycoinstores.com would be great as a hub for merchants to sign up and have support.  Also see that they aren't alone and joining a thriving network.

**Comment by ltanyc** [comment]
done at nycoinstores.com
